spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://localhost:3000"
                allowedOriginPatterns:
                  - "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - "Set-Cookie"
                  - "X-XSRF-TOKEN"
                  - "Authorization"
                allowCredentials: true

          routes:
            - id: book-service
              uri: ${BOOK_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/books/**
              filters:
                - RewritePath=/books/(?<segment>.*), /${segment}

            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/user/**
              filters:
                - RewritePath=/user/(?<segment>.*), /${segment}

            - id: pizza-service
              uri: ${PIZZA_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/pizzeria/**
              filters:
                - RewritePath=/pizzeria/(?<segment>.*), /${segment}

            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/order/**
              filters:
                - RewritePath=/order/(?<segment>.*), /${segment}

            - id: table-service
              uri: ${TABLE_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/table/**
              filters:
                - RewritePath=/table/(?<segment>.*), /${segment}

            - id: socials-service
              uri: ${SOCIALS_SERVICE_URL:http://localhost:8088}
              predicates:
                - Path=/socials/**
              filters:
                - RewritePath=/socials/(?<segment>.*), /${segment}

            - id: file-service
              uri: ${FILE_SERVICE_URL:http://localhost:8089}
              predicates:
                - Path=/files/**
              filters:
                - RewritePath=/files/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web.filter.CorsFilter: DEBUG
