spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    password: postgres
    username: postgres
  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

server:
  port: 8088